// netlify/functions/team-stats.js
// Simple Netlify function that serves team lists and pre-scraped stats
// Uses the JSON files generated by scripts/scraper.js

const allTeams = require('../../data/all-teams.json');
const allStats = require('../../data/all-stats.json');

function jsonResponse(statusCode, bodyObj) {
  return {
    statusCode,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*'
    },
    body: JSON.stringify(bodyObj)
  };
}

exports.handler = async (event) => {
  try {
    const params = event.queryStringParameters || {};
    const leagueParam = params.league;
    const teamParam = params.team;
    const listFlag = params.list;

    if (!leagueParam) {
      return jsonResponse(400, { error: 'Missing "league" query parameter.' });
    }

    const league = leagueParam.toUpperCase();

    const leagueTeams = allTeams[league] || [];
    const leagueStats = allStats[league] || {};

    // If ?list=1 or ?list=true → return just the list of teams for the league
    if (listFlag === '1' || listFlag === 'true') {
      return jsonResponse(200, {
        league,
        teams: leagueTeams
      });
    }

    // Otherwise we expect a team name
    if (!teamParam) {
      return jsonResponse(400, { error: 'Missing "team" query parameter.' });
    }

    const teamName = teamParam.trim();

    // Exact match first
    let stats = leagueStats[teamName];

    // Fallback: case-insensitive match if needed
    if (!stats) {
      const key = Object.keys(leagueStats).find(
        k => k.toLowerCase() === teamName.toLowerCase()
      );
      if (key) stats = leagueStats[key];
    }

    if (!stats) {
      return jsonResponse(404, {
        error: `No stats found for team "${teamName}" in league "${league}".`
      });
    }

    return jsonResponse(200, {
      league,
      team: teamName,
      ...stats
    });
  } catch (err) {
    console.error('team-stats function error:', err);
    return jsonResponse(500, { error: 'Internal server error in team-stats function.' });
  }
};
